### ISSUE TITLE
Youtube history not working

### ISSUE THREAD

**Issue by klikn** [mModule/iYT#1]
When you watch something in the app it is not shown in watch history in the app or youtube.com.

**Comment by ipdev99** [comment]
YouTube watch history is **not** blocked by this module or the ReVanced patches.

Watch history is passed back and forth via the `s.youtube.com` domain.

Normally this issue comes from using an ad blocking app.
-_Might be called a Tracker blocking or Privacy app._
You will have to allow `s.youtube.com` by adjusting the setting of your blocking.

Cheers. :cowboy_hat_face:

**Comment by klikn** [comment]
Thank you ipdev99, you are corr, it was AdAway that was blocking.
